// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(InventarioContext))]
    [Migration("20260908210149_ajuste_localidades_a_clientes")]
    partial class ajuste_localidades_a_clientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Services.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Calle Falsa 123",
                            Created_at = new DateTimeOffset(new DateTime(2026, 9, 8, 18, 1, 48, 686, DateTimeKind.Unspecified).AddTicks(1140), new TimeSpan(0, -3, 0, 0, 0)),
                            Dni = "12345678",
                            Firstname = "Marcelo",
                            IsDeleted = false,
                            Lastname = "Albertissi",
                            LocalidadId = 5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Avenida Siempre Viva 456",
                            Created_at = new DateTimeOffset(new DateTime(2026, 9, 8, 18, 1, 48, 686, DateTimeKind.Unspecified).AddTicks(1191), new TimeSpan(0, -3, 0, 0, 0)),
                            Dni = "87654321",
                            Firstname = "Maria",
                            IsDeleted = false,
                            Lastname = "Gomez",
                            LocalidadId = 5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Calle Real 789",
                            Created_at = new DateTimeOffset(new DateTime(2026, 9, 8, 18, 1, 48, 686, DateTimeKind.Unspecified).AddTicks(1193), new TimeSpan(0, -3, 0, 0, 0)),
                            Dni = "11223344",
                            Firstname = "Pedro",
                            IsDeleted = false,
                            Lastname = "Lopez",
                            LocalidadId = 5
                        });
                });

            modelBuilder.Entity("Services.Models.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Localidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Buenos Aires",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Córdoba",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Santa Fe",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Rosario",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "San Justo",
                            ProvinciaId = 3
                        });
                });

            modelBuilder.Entity("Services.Models.Pais", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Chile"
                        });
                });

            modelBuilder.Entity("Services.Models.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Buenos Aires",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Córdoba",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Chile",
                            PaisId = 1
                        });
                });

            modelBuilder.Entity("Services.Models.Cliente", b =>
                {
                    b.HasOne("Services.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("Services.Models.Localidad", b =>
                {
                    b.HasOne("Services.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Services.Models.Provincia", b =>
                {
                    b.HasOne("Services.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });
#pragma warning restore 612, 618
        }
    }
}
